// Central hooks barrel — re-exports all hooks
export { useApi } from './useApi';
export { useMutation } from './useMutation';
export { useAuth } from './useAuth';
export { useAccountInfo, useBrokerConnection, useAccountSummary, useConnectBroker, useDisconnectBroker } from './useAccount';
export { useMarketData } from './useMarketData';
export { useConnectionStatus } from './useConnectionStatus';
export { useMarketCache, useMarketCandles, useMarketQuote as useCachedMarketQuote, useCacheTimestamp, useCacheFreshness, useCacheSubscriberCount, useMarketCacheActions } from './useMarketCache';
export { useGlobalMarket } from './useGlobalMarket';
export { useTradeSignal, useSignalHistory, useLatestSignal } from './useSignal';
export { useOpenPositions, useExecutionLog, useExecutionSettings, useExecuteOrder, useClosePosition, useCloseAll, useUpdateExecutionSettings } from './useExecution';
export { useHistoryTrades, useHistoryStats, useMonthlyPnl, useStrategyStats } from './useHistory';
export { useRunBacktest, useBacktestHistory, useBacktestStrategies, useBacktestSymbols } from './useBacktest';
export { useAllSettings, useUpdateSettingsSection, useUpdateBroker, useUpdateTradingSettings, useUpdateNotifications, useUpdateAppearance, useUpdateSecurity, useUpdateBackup } from './useSettings';
export { useNotifications } from './useNotifications';
export { useStrategyEvents } from './useStrategyEvents';
export { useSignalId, useSignalIdHistory } from './useSignalId';
export { useSignalValidation } from './useSignalValidation';
export { useSignalLifecycle } from './useSignalLifecycle';
export { useSignalAnalytics } from './useSignalAnalytics';
